### ISSUE TITLE
custom data polygon transform using Polygon-Tutorial2.ipynb

### ISSUE THREAD

**Issue by apanand14** [XinzeLee/PolygonObjectDetection#18]
hello @XinzeLee ,

I'm using my custom dataset and having json file in COCO format. I'm trying to use Polygon-Tutorial2.ipynb for it. But somehow it throws an error. Can you please help me how to run and get rotated bounding boxes from polygon annoations. Thank  you in advance.

This is the error I'm getting:
**Traceback (most recent call last):
  File "C:/yolo/tranform.py", line 173, in <module>
    main()
  File "C:/yolo/tranform.py", line 170, in main
    seg2poly(r'C:\Users\exp', plot=True)
  File "C:/yolo/tranform.py", line 62, in seg2poly
    img_dir = img_dir / prefix
UnboundLocalError: local variable 'prefix' referenced before assignment**

**Comment by yvonnetanyien98** [comment]
Hi, may I ask how to settle this issue? Thank you very much

**Comment by Tracy-git** [comment]
if you use coco format datasets, you are supposed to organize folder like coco20 ,then run Polygon-Tutorial2.ipynb
